version: '3'
services:

  anno-server:
    build: .
    ports:
      - "3333:5000"
    environment:
      - ANNO_LOGLEVEL='debug'
      # - ANNO_ACL_FILE="./acl.yml"
      - ANNO_DIST_DIR=/usr/local/AnnotationService/dist
      # - ANNO_USER_FILE="./users.yml"
      # - ANNO_COLLECTION_FILE="./collections.yml"
      - ANNO_MONGODB_HOST=mongodb
      - ANNO_PORT=3333
      - ANNO_MONGODB_PORT=27017
      - ANNO_ENABLE_JWT_AUTH=true
      - ANNO_SERVER_AUTH='none'
      - ANNO_MIDDLEWARE_PLUGINS=@kba/anno-plugins:PreCollectionFile,
      - ANNO_STORE_HOOKS_PRE=@kba/anno-plugins:PreUserFile,@kba/anno-plugins:CreatorInjectorFile,@kba/anno-plugins:PreAclFile
      - ANNO_STORE_HOOKS_POST=@kba/anno-plugins:CreatorInjectorFile
      - ANNO_STORE=@kba/anno-store-mongodb
      - ANNO_PORT=3000
      - ANNO_OPENAPI_HOST="serv21.ub.uni-heidelberg.de"
      - ANNO_OPENAPI_BASEPATH="/anno"
      - ANNO_BASE_URL="https://serv21.ub.uni-heidelberg.de"
      - ANNO_BASE_PATH="/anno"

  mongodb:
    image: "mongo:3"
