version: '3'

services:

  anno-server:
    image: kbai/anno-common
    ports:
      - 3333:3333
    volumes:
      - ./config:/anno-config
    environment:
      - ANNO_LOGLEVEL=debug
      - ANNO_PORT=3333
      - ANNO_STORE=@kba/anno-store-mongodb
      - ANNO_MONGODB_HOST=mongodb
      - ANNO_MONGODB_PORT=27017
      - ANNO_ACL_FILE=/anno-config/acl.yml
      - ANNO_USER_FILE=/anno-config/users.yml
      - ANNO_COLLECTION_FILE=/anno-config/collections.yml
      - ANNO_ENABLE_JWT_AUTH=true
      - ANNO_SERVER_AUTH=plain
      - ANNO_MIDDLEWARE_PLUGINS=@kba/anno-plugins:PreCollectionFile,
      - ANNO_STORE_HOOKS_PRE=@kba/anno-plugins:PreUserFile,@kba/anno-plugins:CreatorInjectorFile,@kba/anno-plugins:PreAclFile
      - ANNO_STORE_HOOKS_POST=@kba/anno-plugins:CreatorInjectorFile
      - ANNO_BASE_URL=http://serv21.ub.uni-heidelberg.de
      - ANNO_BASE_PATH=/anno
      - OPENAPI_HOST=localhost:3333
      - OPENAPI_BASEPATH=/
      - OPENAPI_PATH=anno

  mongodb:
    image: "mongo:3"
    ports:
      - 27017:27017
